microsoft/spektate

- src/Dashboard.tsx
- src/css/dashboard.css
- Max width for the App is now 100vw
- The table is now `overflow: scroll` for horizontal scrolling
> Added 100vw max-width

- src/Dashboard.tsx
- src/Dashboard.types.ts
- src/cli/AccessHelper.ts
- src/cli/cli.ts
- src/models/Deployment.ts
- src/models/pipeline/AzureDevOpsPipeline.ts
- src/models/pipeline/Build.ts
- src/models/pipeline/Pipeline.ts
- src/models/pipeline/Release.ts
- src/models/repository/Author.ts
- src/models/repository/AzureDevOpsRepo.ts
- src/models/repository/GitHub.ts
- src/models/repository/Repository.ts
- src/models/repository/Tag.ts
- Refactored some classes to just be interfaces instead.
> Refactored classes to be interfaces instead

- src/Dashboard.tsx
- src/cli/AccessHelper.ts
- src/models/Deployment.ts
- src/models/HttpHelper.ts
- src/models/pipeline/AzureDevOpsPipeline.ts
- src/models/pipeline/Pipeline.ts
- src/models/repository/AzureDevOpsRepo.ts
- src/models/repository/GitHub.ts
- src/models/repository/Repository.ts
- refactored some models/functions to be promise based instead of callback
> migrate from callbacks to promises

- README.md
I believe that the displayName on this example is off by two spaces such that when you copy and paste it, it does not work in azure-pipelines.yaml
> Indent display name by two spaces

- src/Dashboard.tsx
Currently set to a 30 second interval, do you think this interval is too long?
> Auto refreshing deployments 

- README.md
- src/Dashboard.tsx
- src/cli/AccessHelper.ts
- src/cli/spex.ts
- src/models/Deployment.ts
- src/tests/Basic.test.ts
- src/tests/PrivateGitHub.test.ts
- Adding a filter for service in the cli
- display the service column in cli
Closes #28
> Adding filter for service in CLI

- package-lock.json
- package.json
- packages/spektate/package-lock.json
- packages/spektate/package.json
- packages/spektate/src/Deployment.ts
- packages/spektate/src/pipeline/AzureDevOpsPipeline.ts
- src/Dashboard.tsx
- src/config.ts
Author column was missing because for private repos, it needs a personal access token to get that information. 
Once this PR is approved, do the following:
Related to https://github.com/microsoft/bedrock/issues/707
> Fix missing author info for private repos

- package-lock.json
- package.json
- packages/spektate/package-lock.json
- packages/spektate/package.json
- packages/spektate/src/Deployment.ts
- packages/spektate/src/pipeline/AzureDevOpsPipeline.ts
- packages/spektate/src/pipeline/Build.ts
- packages/spektate/src/pipeline/Release.ts
- src/Dashboard.tsx
Closes https://github.com/microsoft/bedrock/issues/715
> Icon and duration fix, and some sorting

- packages/spektate/package-lock.json
- packages/spektate/src/Deployment.ts
- src/Dashboard.tsx
- src/Dashboard.types.ts
- src/DeploymentFilter.tsx
- src/css/dashboard.css
Closes https://github.com/microsoft/bedrock/issues/736
> Dashboard filters 

- package-lock.json
- package.json
- packages/spektate/package.json
- packages/spektate/src/Deployment.ts
- src/Dashboard.tsx
Related to https://github.com/microsoft/bedrock/issues/739
> Add fillers to holes in dashboard

- package-lock.json
- package.json
- packages/spektate/package.json
- packages/spektate/src/repository/Author.ts
- packages/spektate/src/repository/AzureDevOpsRepo.ts
- packages/spektate/src/repository/GitHub.ts
- src/Dashboard.tsx
PR build is going to fail since new npm package needs to be created. Will do on approval.
> Adding a persona icon for authors

- package-lock.json
- package.json
- packages/spektate/package-lock.json
- packages/spektate/package.json
- packages/spektate/src/Deployment.ts
- src/Dashboard.tsx
- src/Dashboard.types.ts
- src/DeploymentFilter.tsx
Closes https://github.com/microsoft/bedrock/issues/761
> Save filters in query params and apply them on load

- packages/spektate/src/pipeline/AzureDevOpsPipeline.ts
Closes https://github.com/microsoft/bedrock/issues/809
> Dashboard points to incorrect link for commit id

- packages/spektate/src/Deployment.ts
- packages/spektate/src/pipeline/Build.ts
- packages/spektate/src/repository/AzureDevOpsRepo.test.ts
- packages/spektate/src/repository/AzureDevOpsRepo.ts
- packages/spektate/src/repository/GitHub.test.ts
- packages/spektate/src/repository/GitHub.ts
- packages/spektate/src/repository/Repository.ts
- packages/spektate/src/repository/Tag.ts
- packages/spektate/src/repository/mocks/github-sync-response-1.json
- packages/spektate/src/repository/mocks/github-sync-response.json
- src/Dashboard.tsx
- src/Dashboard.types.ts
Closes https://github.com/microsoft/bedrock/issues/814
> Read multiple flux syncs

- src/css/dashboard.css
> Reduce height of header

- package-lock.json
- package.json
- packages/spektate/package-lock.json
- packages/spektate/package.json
- packages/spektate/src/Deployment.ts
- packages/spektate/src/HttpHelper.ts
- packages/spektate/src/pipeline/AzureDevOpsPipeline.test.ts
- packages/spektate/src/repository/AzureDevOpsRepo.test.ts
- packages/spektate/src/repository/AzureDevOpsRepo.ts
- packages/spektate/src/repository/GitHub.test.ts
- packages/spektate/src/repository/GitHub.ts
- packages/spektate/src/repository/Repository.ts
- src/Dashboard.tsx
- src/Dashboard.types.ts
Opening this PR to start getting early feedback on the UI. 
- Added a column that shows up only when there is cluster information to show
- Refactored some code in fetch author
Closes https://github.com/microsoft/bedrock/issues/840
> Cluster column in dashboard

- package.json
- packages/spektate/package.json
- packages/spektate/src/pipeline/AzureDevOpsPipeline.ts
- yarn.lock
Closes https://github.com/microsoft/bedrock/issues/1092
> Fix bug where single row of data is not showing up

- packages/spektate/src/IDeployment.test.ts
- packages/spektate/src/IDeployment.ts
- packages/spektate/src/pipeline/AzureDevOpsPipeline.test.ts
- packages/spektate/src/pipeline/AzureDevOpsPipeline.ts
- src/backend/index.ts
1. code simplification
2. correct Deployment so that we will not get logger error when test fails
3. added return type for some function
4. remove parse function middeware in express app.
> added tests and code cleanup

- packages/spektate/src/IDeployment.ts
Resolves: [Bedrock 1124](https://github.com/microsoft/bedrock/issues/1124)
> Add error message

- README.md
- chart/.helmignore
- chart/Chart.yaml
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/ingress.yaml
- chart/templates/loadbalancer.yaml
- chart/templates/service.yaml
- chart/values.yaml
- package.json
- packages/spektate/package.json
Dashboard is running at http://13.89.237.230/? that was deployed using this helm chart, and the command below:
`helm install . --name spektate --set storageAccessKey=*** --set storageTableName=deployments --set storagePartitionKey=hello-bedrock-azure-private --set storageAccountName=saakhtacjteststorage --set pipelineProject=hellobedrockprivate --set pipelineOrg=epicstuff --set pipelineAccessToken=*** --set manifest=hello-bedrock-azure-private-manifest --set manifestAccessToken=*** --set githubManifestUsername=  --set sourceRepoAccessToken=***`
Closes https://github.com/microsoft/bedrock/issues/967
> Helm chart

- packages/spektate/src/IDeployment.ts
- src/backend/clustersync.ts
- src/backend/deployment.ts
- src/client/Dashboard.tsx
Closes https://github.com/microsoft/bedrock/issues/1238
> Adding support for waiting icon and failed icon in status

- packages/spektate/src/repository/IAzureDevOpsRepo.ts
Closes https://github.com/microsoft/bedrock/issues/1280
> Fixing bug with pr fetch

- package.json
- packages/spektate/package.json
- packages/spektate/src/IDeployment.ts
- packages/spektate/src/repository/IGitHub.ts
- src/client/Dashboard.tsx
- src/client/Dashboard.types.ts
- src/client/DeploymentFilter.tsx
- src/client/css/dashboard.css
- yarn.lock
- Changed yellow warning icon to red
- Changed the colors of red, yellow, gray, blue and green to match colors from this [page](https://projects.susielu.com/viz-palette?colors=%5B%22#2aa05b%22,%22%23e08a00%22,%22%23c8281f%22%5D&backgroundColor=%22white%22&fontColor=%22black%22&mode=%22normal%22).
... and other tasks under https://github.com/microsoft/bedrock/issues/1261 
Closes https://github.com/microsoft/bedrock/issues/1261
> Updating icons

- packages/spektate/package.json
- packages/spektate/yarn.lock
The lack of this package was giving issues. See [here](https://dev.azure.com/abrig/spk/_build/results?buildId=1676&view=logs&j=16639f5d-f408-53eb-ed05-a63768a37735&t=54f22e62-9852-5649-8d54-bd6afbd36d8f)
> Adding tslint-config-prettier

- README.md
- packages/spektate/README.md
- packages/spektate/package.json
Closes https://github.com/microsoft/bedrock/issues/878 
Package README is also at https://www.npmjs.com/package/spektate
> Adding README for spektate and release instructions for package and docker

- package.json
- packages/spektate/package.json
- packages/spektate/src/repository/IGitHub.ts
- yarn.lock
Closes https://github.com/microsoft/bedrock/issues/1338 
See here for bug in action: http://104.43.143.180/
> Fixing URL for github PRs

- package.json
- packages/spektate/package.json
- packages/spektate/src/repository/IAzureDevOpsRepo.ts
- yarn.lock
Closes https://github.com/microsoft/bedrock/issues/1334 
Falling back to using the authenticated URL
> Use correct image URL for merged by author; this does not need authentication

- src/client/Dashboard.tsx
- src/client/DeploymentTable.tsx
- src/client/Table.tsx
- src/client/cells/build.tsx
- src/client/cells/cluster.tsx
- src/client/cells/icons.tsx
- src/client/cells/persona.tsx
- src/client/cells/simple.tsx
- src/client/cells/status.tsx
- src/client/cells/time.tsx
And removed the use of anys in client side. 
Closes https://github.com/microsoft/bedrock/issues/1244
> Refactor: Splitting dashboard.tsx to more components

- package.json
- packages/spektate/package.json
- packages/spektate/src/repository/IAzureDevOpsRepo.test.ts
- packages/spektate/src/repository/IAzureDevOpsRepo.ts
- packages/spektate/src/repository/IGitHub.test.ts
- packages/spektate/src/repository/IGitHub.ts
- src/client/Dashboard.tsx
- yarn.lock
And handling some nulls
Closes https://github.com/microsoft/bedrock/issues/1364
> Cluster sync bug fix

- backend/package.json
- backend/yarn.lock
- frontend/src/DeploymentTable.tsx
Closes https://github.com/microsoft/bedrock/issues/1382 
Presence of undefineds was causing this behavior
Deployed at http://52.149.54.124:5000/
> Merged by sort fix

- backend/package.json
- backend/yarn.lock
- frontend/package.json
- frontend/src/Dashboard.tsx
- frontend/src/DeploymentFilter.tsx
- frontend/src/DeploymentTable.tsx
- frontend/src/cells/build.tsx
- frontend/src/cells/cluster.tsx
- frontend/src/cells/icons.tsx
- frontend/src/cells/time.tsx
- frontend/src/registerServiceWorker.ts
- frontend/yarn.lock
- Bumped TypeScript related dependencies
- Upgraded to Prettier V2
- Ran prettier on `src`
> Dev Dependency Bump

- backend/src/lib/cache.test.ts
- backend/src/lib/cache.ts
- deploy/deploy-spektate-ci.yaml
Closes https://github.com/microsoft/bedrock/issues/1398 
Deployed at http://52.149.54.124:5000/
> Catch and log error silently if author/pr calls fail

- frontend/src/DeploymentTable.tsx
- frontend/yarn.lock
Close https://github.com/microsoft/bedrock/issues/1404.
> Rename columns for Spektate dashboard

- frontend/src/Dashboard.tsx
- frontend/src/Dashboard.types.ts
- frontend/src/DeploymentFilter.tsx
- frontend/src/DeploymentTable.tsx
- frontend/src/cells/simple.tsx
- frontend/src/css/dashboard.css
Closes https://github.com/microsoft/bedrock/issues/1372
Deployed at http://52.149.54.124:5000/ 
- We fixed a bug with filtering which was causing filters to not be applied from query params
- Added the text "Manual HLD Edit" to be displayed under the ACR to HLD column - **please provide feedback on this experience**
- Added a type filter which defaults to "Bedrock Deployments" unless the user has chosen to select filters to show otherwise
> Better dashboard experience for manual HLD edited deployments

- backend/package.json
- backend/src/config.test.ts
- backend/src/config.ts
- backend/src/lib/clustersync.test.ts
- backend/src/lib/deployments.ts
- backend/src/lib/test-common.ts
- backend/yarn.lock
- frontend/package.json
- frontend/src/Dashboard.tsx
- frontend/src/cells/icons.tsx
- frontend/src/index.tsx
- frontend/yarn.lock
- packages/spektate/package.json
- packages/spektate/src/HttpHelper.ts
- packages/spektate/src/IDeployment.ts
- packages/spektate/src/pipeline/GithubActions.test.ts
- packages/spektate/src/pipeline/GithubActions.ts
- packages/spektate/src/pipeline/Release.ts
- packages/spektate/src/pipeline/index.ts
- packages/spektate/src/pipeline/mocks/gh-actions-1115488431.json
- packages/spektate/src/pipeline/mocks/gh-actions-1255355142.json
- packages/spektate/yarn.lock
sample dashboard http://40.91.93.178:5000/
> GitHub actions support 
